# Generated by Django 4.1 on 2022-09-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachbase_id', models.IntegerField(unique=True, verbose_name='id в teachbase')),
                ('name', models.CharField(max_length=200, verbose_name='наименование')),
                ('description', models.TextField(blank=True, default='', verbose_name='описание')),
                ('duration', models.IntegerField(blank=True, default=None, null=True, verbose_name='продолжительность (сек.)')),
                ('bg_url', models.URLField(blank=True, default='', null=True, verbose_name='bg_url')),
                ('video_url', models.URLField(blank=True, default='', null=True, verbose_name='URL video')),
            ],
            options={
                'verbose_name': 'Курс Teachbase',
                'verbose_name_plural': 'Курсы Teachbase',
            },
        ),
    ]
